version: '3'
services:
  registry:
    image: descartesresearch/teastore-registry
    platform: linux/amd64
    expose:
      - "8080"

  db:
    image: descartesresearch/teastore-db
    platform: linux/amd64
    expose:
      - "3306"
    ports:
      - "3306:3306"

  persistence:
    image: descartesresearch/teastore-persistence
    platform: linux/amd64
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"

  auth:
    image: descartesresearch/teastore-auth
    platform: linux/amd64
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"

  image:
    image: descartesresearch/teastore-image
    platform: linux/amd64
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"

  recommender:
    image: descartesresearch/teastore-recommender
    platform: linux/amd64
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"

  webui:
    image: descartesresearch/teastore-webui
    platform: linux/amd64
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    ports:
      - "8080:8080"